### ISSUE TITLE
Running "npm run e2e" opens the WebDriver instances but nothing happens...

### ISSUE THREAD

**Issue by FJLopezGarcia** [wswebcreation/protractor-cucumber-typescript-boilerplate#5]
Hi, 
First of all thanks for this repository!!!

I have cloned the repository
I have run an "npm install"
I have started the webdriver-manager with "webdriver-manager start"
but when i run for example an "npm run e2e -- --feature=example" the instances open but nothing happens...  Do you know what is happening? am I missing something?

![image](https://user-images.githubusercontent.com/6631983/31956530-ffee1640-b8eb-11e7-97de-d7fa2c83fbe8.png)
 
Thanks a lot for your help!!

**Comment by wswebcreation** [comment]
Hi @FJLopezGarcia 

Sorry, this is my fault. The build has been broken since CucumberJS 3.0.4, but I hadn't had the time to check this out. If you set `shardTestFiles: false` you will get more error log. Then you get an error like this `Error: empty stack`. This is caused by the change in CucumberJS 3.0.4 because, as far as I can see, `protractor-cucumber-framework` passes `cucumberOpts.tags:''` as `--tags undefined` which will now make CucumberJS break.

I've added an issue, see [here](https://github.com/protractor-cucumber-framework/protractor-cucumber-framework/issues/113) and a [fix](https://github.com/protractor-cucumber-framework/protractor-cucumber-framework/pull/114) to the `protractor-cucumber-framework`. If it is accepted and a new release is made I'll update my boilerplate and it will work again

**Comment by FJLopezGarcia** [comment]
ok.. thanks... waiting for the fix!! thanks a lot again for the project and thanks for the quick answer.

**Comment by wswebcreation** [comment]
Hi @FJLopezGarcia 

I've update the template, the only thing you need to do is upgrade protractor-cucumber-framework to version 4.1.1. That holds the fix to make everything work again. Within a few minutes the build will also be green for NodeJS 6,7 and 8.

Good luck with it

**Comment by FJLopezGarcia** [comment]
Thanks a lot!!
